Add `aliases` to settings
aziz/SublimeHyperClick pull request #43
Opened 2019-01-27 02:57 UTC by julianburr

A bit of a long shot, but I think this might be helpful for reference even if it doesn't get merged :smile:

This adds a new setting `aliases` for the plugin, which allows you to specify path aliases e.g. for webpack or babel aliases. Main reason for a seperate setting is that aliases not necessarily have the same name as the real directory they are pointing to, so lookup folder settings etc. don't work a lot of the time.

So this PR adds the following:

```json
{
  "aliases": {
    "js": {
      "@components": "./src/components"
    }
  }
}
```

The js resolver will check if the import starts with any of the defined aliases first and will replace it with the given source path.

This PR kind of addresses a few issues (https://github.com/aziz/SublimeHyperClick/issues/36, https://github.com/aziz/SublimeHyperClick/issues/15, https://github.com/aziz/SublimeHyperClick/issues/5), but it doesn't really solve the core problem. It only allows you to define global aliases (which works for me cause I usually have the same in all my project), but ideally you should be able to define these per project + be able to pull them in from other configs e.g. in the package json. However here we run into the usual issue that there are a bazillion ways to define aliases (at least for JS bundlers) + I don't know how to read out configs from other files in python in a performant manner 😅

2019-01-28 03:21 UTC, diandian18 commented
Great !

2019-03-15 10:05 UTC, niksy commented
@aziz can we get this merged?

2019-05-05 10:11 UTC, anru requested changes

2019-05-05 10:11 UTC, anru commented on hyper_click/js_path_resolver.py
> +        print('resolve from alias', alias, alias_source)
Looks like it's debug print

```suggestion
```

2019-05-05 10:11 UTC, anru commented on hyper_click/js_path_resolver.py
> +            result = self.resolve_relative_to_dir(self.str_path, self.currentRoot)
Could you show example why do we need this case ?

2019-05-05 10:11 UTC, anru commented on hyper_click/js_path_resolver.py
> +            alias_path = alias_source + self.str_path[len(alias):]
Looks like `path.join` is more robust way for building paths

```suggestion
            alias_path = path.join(alias_source, self.str_path[len(alias):])
```

2019-09-19 13:57 UTC, drew-wallace commented
Let's get this merged

2020-01-05 17:44 UTC, merged

2020-01-05 17:55 UTC, cristianl commented
Thanks! It doesn't take into account project settings (_.sublime-project_ files). I'll fix it later

2020-01-09 20:32 UTC, cristianl commented
Shipped in [1.11.0](https://github.com/aziz/SublimeHyperClick/releases/tag/1.11.0).